export  const MySchoolData = [
    {
      id: 1,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=12",
      reg: "050003921",
    },
    {
      id: 2,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=5",
      reg: "050003921",
    },
    {
      id: 3,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=1",
      reg: "050003921",
    },
    {
      id: 4,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=2",
      reg: "050004532",
    },
    {
      id: 5,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=3",
      reg: "050004532",
    },
    {
      id: 6,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=4",
      reg: "050004532",
    },
    {
      id: 7,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=5",
      reg: "050004532",
    },
    {
      id: 8,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=6",
      reg: "050004532",
    },
    {
      id: 9,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=7",
      reg: "050004532",
    },
    {
      id: 10,
      name: "Jane Doe",
      class: "XI",
      roll: 12,
      avatar: "https://i.pravatar.cc/40?img=8",
      reg: "050004532",
    },
     {
      id: 11,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=9",
      reg: "050003921",
    },
     {
      id: 12,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=10",
      reg: "050003921",
    },
     {
      id: 13,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=11",
      reg: "050003921",
    },
     {
      id: 14,
      name: "John Tripathi",
      class: "XII",
      roll: 27,
      avatar: "https://i.pravatar.cc/40?img=12",
      reg: "050003921",
    },
  ];